In [1]:
import pandas as pd
import numpy as np

In [2]:
arr1 = np.arange(0,11)
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Now to acces the elements of the array we will have to know the index of the elements in the array. The index of the
array starts from 0.

In [3]:
arr1[2] , arr1[3]

(2, 3)

# Now we define a new array

In [4]:
arr2 = np.arange(10,21)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr1[2], arr2[4] 
#we can print the elements of multiple arrays in one line as well by the name of the array and the correct index

(2, 14)

# Slicing


In [6]:
arr1[0:5]  #Here we created a slice for the array.

array([0, 1, 2, 3, 4])

In [7]:
arr2[2:5]  #we can give the starting point as well as the ending point.

array([12, 13, 14])

In [8]:
arr1[:5] # If we do not give a starting point it will asssume the starting point at o and vice versa.

array([0, 1, 2, 3, 4])

In [9]:
arr1[-1]  , arr2[-5:]                     #here we can access the elements from the end of the array.

(10, array([16, 17, 18, 19, 20]))

# Broadcasting


In [10]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr1[0:4]=100    #It is a feature wherein we can replace multiple values in an array with a particular value.
arr1

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [12]:
arr1= np.arange(0,11) #we reset the array here.
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can also copy an array with the help of the copy method.

In [13]:
arrcopy = arr1.copy() #Copying an existing array in a new array.
arrcopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2-D Arrays

In [14]:
arr2d = np.array([[12,2,0],[41,15,66],[17,58,69]])
arr2d

array([[12,  2,  0],
       [41, 15, 66],
       [17, 58, 69]])

In [15]:
#If we want to access a row in an array we can

arr2d[0]

array([12,  2,  0])

In [16]:
arr2d[1,2]  # If we want to access only on element we will have to give two coordinates.

66

In [17]:
arr2d[:,1]   #we can index a column in array.

array([ 2, 15, 58])

In [18]:
ae=arr2d[:2,:2]
ae

array([[12,  2],
       [41, 15]])

# Conditional Selection

In [19]:
arr2d > 50 #Here we are checking if the elements of the matrix are greater than 5. It gives boolean values.

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [20]:
arr2d[arr2d>30] # Here we are checking if the elements of the array are greater than 30 and printing them.

array([41, 66, 58, 69])

In [21]:
arr2d[:,(0,1)]  # We can also index an array like this.

array([[12,  2],
       [41, 15],
       [17, 58]])

In [22]:
arr2d[:,(0,1)] >10  #we can check if the selected entries are correct against the condition.

array([[ True, False],
       [ True,  True],
       [ True,  True]])

# To read a file using Pandas

In [23]:
#We create a dataframe and give it a name. 
#We also have to select the format in which we can select the format of the file to be selected.

#df1 = pd.read_csv("address")

In [24]:
df0 = pd.read_csv('C:\\Users\\Prakhar\\Downloads\\sample1.csv')
df0

1   2   3   4   5
0   6   7   8   9  10
1  11  12  13  14  15

In [25]:
from numpy.random import randn

In [26]:
np.random.seed(101)

In [27]:
df1 = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df1   #(Ist Method) we use the split function here to separate indexes and columns. #dataframe creation

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df2= pd.DataFrame(randn(5,4),index =["A","B","C","D","E"],columns = ["1",'2','3','4'])
df2   #We can use inverted commas to define the column and indexes.

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [29]:
#we can access an index in a dataframe as well.
df2["1"]

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: 1, dtype: float64

In [30]:
# if we want to access more than one column at the same time we'll have to use double brackets.
df2[['1','2']]

1         2
A  0.302665  1.693723
B -0.134841  0.390528
C  0.807706  0.072960
D -0.497104 -0.754070
E -0.116773  1.901755

In [31]:
df2.loc[['A'],['1','2']]   #We can use the loc method for accessing a certain row in a data frame.

1         2
A  0.302665  1.693723

In [32]:
df2.loc[['A','B'],['1','2']]  #WE CAN ACCESS MULTIPLE ROWS AS WELL.

1         2
A  0.302665  1.693723
B -0.134841  0.390528

In [33]:
df2["5"]="4 3 6 7 9".split() #we can add a column in the data frame like this. 
df2

1         2         3         4  5
A  0.302665  1.693723 -1.706086 -1.159119  4
B -0.134841  0.390528  0.166905  0.184502  3
C  0.807706  0.072960  0.638787  0.329646  6
D -0.497104 -0.754070 -0.943406  0.484752  7
E -0.116773  1.901755  0.238127  1.996652  9

Dropping Columns in Dataframes


In [34]:
df2.drop('5',axis=1)

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [35]:
df2  #we can see here that the column was only dropped temporarily.

1         2         3         4  5
A  0.302665  1.693723 -1.706086 -1.159119  4
B -0.134841  0.390528  0.166905  0.184502  3
C  0.807706  0.072960  0.638787  0.329646  6
D -0.497104 -0.754070 -0.943406  0.484752  7
E -0.116773  1.901755  0.238127  1.996652  9

In [36]:
df2.drop('5',axis=1,inplace=True)
df2    #Here the column was changed in the original dataframe.

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [37]:
#Now let's try to drop a row.
df2.drop('E')
#E was dropped here, but it won't be changed permanently in the dataframe since inplace is not equal to true.

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [38]:
df2

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

#### We can two ways for indexing rows, using iloc and loc.

In [39]:
df2.loc[['A','B'],['1','2','3','4']]   #HERE WE MARKED BOTH THE COLUMNS AND ROWS USING LOC.

1         2         3         4
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502

In [40]:
df2.loc['A','1']   #we can access single values in the matrix like this.

0.3026654485851825

In [41]:
df2.iloc[['2','4']]  #we can use iloc to directly access the rows in the dataframe. #ILOC SELECTS COMPLETE ROWS.

1         2         3         4
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [42]:
df2.iloc[2]  #it can give all the values contained in the row.

1    0.807706
2    0.072960
3    0.638787
4    0.329646
Name: C, dtype: float64

In [61]:
df3=pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns= '1 2 3 4 '.split())
df3

1         2         3         4
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

# CONDITIONAL SELECTING

#We can select a certain column/row in a matrix and check if the elements are fullfilling a certain condition or not.

In [44]:
df3['1']>0

A    False
B     True
C     True
D     True
E    False
Name: 1, dtype: bool

In [45]:
bool1 = df3['1']>0
bool1

A    False
B     True
C     True
D     True
E    False
Name: 1, dtype: bool

In [46]:
df3[bool1]#we can observe here that the bool command has removed the rows which do not satisfy the condition.

1         2         3         4
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [47]:
df3[bool1]['1']  #Here the entry was removed which did not satisfy the condition.

B    1.025984
C    2.154846
D    0.147027
Name: 1, dtype: float64

In [48]:
df3[bool1][['1','2']]

1         2
B  1.025984 -0.156598
C  2.154846 -0.610259
D  0.147027 -0.479448

In [49]:
df3>0

1      2      3      4
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [50]:
df3[df3>0]

1         2         3         4
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [62]:
df3[(df3['1']>0) & (df3['4']>0)] #Here two conditions are being checked.

1         2         3         4
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
E  0.992573  1.192241 -1.046780  1.292765

In [78]:
df3[(df3['1']>0) & (df3['4']>0)][['1','4']]

1         4
A  0.386030  0.230336
B  0.681209  1.939932
E  0.992573  1.292765

###### We can add completely new indexes in the data frame.

In [ ]:
new_index = ' India Japan China USA Spain'.split()
new_index

In [ ]:
df3['country']= new_index
df3

In [ ]:
df3.set_index('country')

# GroupBy

In [ ]:
fox1 = {'company':['Google','Google','Morgan Stanley','Facebook','Facebook','Morgan Stanley'],'Employee':['Rachel','Monika','Phoebe','Ross','Chandler','Joey'],
        'Sales':[56,78,65,53,67,87]}

In [ ]:
df4 = pd.DataFrame(fox1)
df4

In [ ]:
groupbydf4 = df4.groupby('company')

#Now we will be using the groupby function to group together the common elements ina  a dataframe.

In [ ]:
df4.groupby('company').sum()

In [ ]:
groupbydf4.sum().loc['Facebook']

In [ ]:
groupbydf4.sum().loc[['Google','Facebook']]

In [ ]:
groupbydf4.min()  #It can be used for grouping a certain attribute from minimum to max.

In [ ]:
groupbydf4.max()  #It can  be used for finding the max value in the various groups.

In [ ]:
groupbydf4.describe()  #we can get the details about the data set.

In [ ]:
groupbydf4.describe().transpose()  #we can get the transposed details for the data set.

In [ ]:
df5 = pd.DataFrame({'A': ['A1','A2','A3','A4','A5'],
                   'B': ['B1','B2','B3','B4','B5'],
                   'C': ['C1','C2','C3','C4','C5'],
                   'D': ['D1','D2','D3','D4','D5']},
                   index = [0,1,2,3,4])
df5

In [ ]:
df6 = pd.DataFrame({'A' : ['A6','A7','A8','A9','A10'],
                    'B': ['B6','B7','B8','B9','B10'],
                    'C': ['C6','C7','C8','C9','C10'],
                    'D': ['D6','D7','D8','D9','D10']},
                  index = [4,5,6,7,8])

df6

In [ ]:
df7 = pd.DataFrame({'A': ['A11','A12','A13','A14','A15'],
                    'B': ['B11','B12','B13','B14','B15'],
                    'C': ['C11','C12','C13','C14','C15'],
                    'D':['D11','D12','D13','D14','D15']},
index = [9,10,11,12,13])
df7

# CONCATENATION 


Concatenation can be used for combining data frames together by the pd.concat method.
By default if dataframes are combined with each other they will be joined together one after the other, i.e axis = 0.

In [ ]:
pd.concat([df5,df6,df7]) #Here we combined the rows with rows.


In [ ]:
pd.concat([df5,df6,df7],axis=1)

### Now we will create dataframes which have the same axis.


In [ ]:
df8 = pd.DataFrame({'A': ['A1','A2','A3','A4','A5'],
                   'B': ['B1','B2','B3','B4','B5'],
                   'C': ['C1','C2','C3','C4','C5'],
                   'D': ['D1','D2','D3','D4','D5']},
                   index = [0,1,2,3,4])
df8

In [ ]:
df9 = pd.DataFrame({'A' : ['A6','A7','A8','A9','A10'],
                    'B': ['B6','B7','B8','B9','B10'],
                    'C': ['C6','C7','C8','C9','C10'],
                    'D': ['D6','D7','D8','D9','D10']},
                  index = [0,1,2,3,4])

df9

In [ ]:
df10 = pd.DataFrame({'A': ['A11','A12','A13','A14','A15'],
                    'B': ['B11','B12','B13','B14','B15'],
                    'C': ['C11','C12','C13','C14','C15'],
                    'D':['D11','D12','D13','D14','D15']},
index = [0,1,2,3,4])
df10

In [ ]:
pd.concat([df8,df9,df10])

In [ ]:
pd.concat([df8,df9,df10],axis=1) #Here we combined the data frames on the same axis, and they have the same indexes.

# Merging


##### We can merge together various available dataframes together with the help of various join which are available such as inner
##### join, left join , right join etc.


In [ ]:
df11 = pd.DataFrame({
    'key' : ['1','2','3','4'],
    'A': ['A1','A2','A3','A4'],
    'B': ['B1','B2','B3','B4']
})

df12 = pd.DataFrame({
    'key': ['1','2','3','4'],
    'A1': ['A5','A6','A7','A8'],
    'B1': ['B5','B6','B7','B8']
})


df11


In [ ]:
df12

#Here we are going to merge two data frames on the basis of 'key'.The key column is common in both the data frames and can be used for finding common rows in both the data frames.

In [ ]:
pd.merge(df11,df12,how = 'inner', on = 'key')

# JOINS


The concept of joins can be used for 

In [ ]:
left = pd.DataFrame({
    'A': ['A1','A2','A3','A4'],
    'B': ['B1','B2','B3','B4']},
    index=['1','2','3','4'])
left

In [ ]:
right = pd.DataFrame({
    'C': ['C1','C2','C3','C4'],
    'D':['D1','D2','D3','D4']},
    index=['1','3','4','5']
)
right

In [ ]:
left.join(right)  #Here the indexes will be used for joining two data frames together.

In [ ]:
right.join(left)

In [ ]:
left.join(right, how='inner')  #inner join will be only be used for joining common elements together in two data frames.

In [ ]:
left.join(right, how='outer') #Here all the elements will be included from both the data frames, with missing values being filled as nan. 
                                 

# Missing Data

If there is some missing data in the data frame it will be filled as NaN.
We use various ways to fill in the blanks such as mean, median or mode.

In [ ]:
d = {'A' :[1,np.nan,3],
    'B':[4,np.nan,np.nan],
    'C' : [7,8,9]}

# Here we created a dataframe using a dictionary.
#This method is easier.
    

In [ ]:
df13 = pd.DataFrame(d)
df13

In [ ]:
df13.dropna()
# Here the function dropna was used for dropping the indexes which contained NaN.

In [ ]:
df13.dropna(axis=1) #Here the axis was 1 and the only column which did not contain NaN was not dropped. 

### Thresh is used for getting the rows which contain the minimum designated thresh values.


In [ ]:
df13.dropna(thresh=2)

In [ ]:
df13.dropna(thresh=3)

### We use 'fillna' for filling the missing values of a dataframe.

In [ ]:
df13.fillna('miss')  #Here the missing values were highlighted.

In [ ]:
df13['A'].fillna(value = df13['A'].mean())

### Here we are creating a multi-index. Here each index belongs to a main index.

In [66]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hierarch_index = list(zip(outside,inside))

In [67]:
hierarch_index= pd.MultiIndex.from_tuples(hierarch_index)
hierarch_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

# doubt for the code


In [68]:
df_1 = pd.DataFrame(np.random.randn(6,3),index= pd.MultiIndex.from_tuples(hierarch_index),columns = 'A B C'.split())
df_1

A         B         C
G1 1 -1.467514 -0.494095 -0.162535
   2  0.485809  0.392489  0.221491
   3 -0.855196  1.541990  0.666319
G2 1 -0.538235 -0.568581  1.407338
   2  0.641806 -0.905100 -0.391157
   3  1.028293 -1.972605 -0.866885

In [ ]:
df_1.loc['G1'] #Here we extract an index which contains further indexes.

In [ ]:
df_1.loc['G1'].loc[[1,2]]  #Here we extracted a main index and then extracted the inside indexes by loc.

In [ ]:
df_1.iloc[0]

### Here the names of the outside and inside indexes have not been done. We can so so on the following way:


In [ ]:
df_1.index.names = ['Group','Num']
df_1

# Arrays

Now we define arrays with the help of np.arrays(list) command. This will convert the list into an array.

In [ ]:
my_list = [1,2,3,4,5]


In [ ]:
np.array(my_list)  #Here we defined an array with the help of a list.

In [ ]:
arr1 = np.array(my_list) #Here we gave a name to the array.

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] #Here we will defined a matrix.

In [ ]:
np.array(my_matrix)  # A matrix is a 2-dimensional array.

In [ ]:
matrix1 = np.array(my_matrix)  #HERE WE ASSIGNED A NAME TO THE MATRIX.

### We can use various methods to define arrays by numpy.

In [ ]:
np.arange(0,20,2)  #Here we gave a range as well the intervals which need to be followed.

In [ ]:
np.arange(0,5)

If we want an array of zeroes and ones we can use the 'ones' and 'zeros' method.

In [ ]:
np.zeros(5)

In [ ]:
np.ones((6,6))  # Here we created an 2-d array of ones.

# Linspace

We can use linspace for generating a seqeunce of values between two numbers which are evenly spaced. We can decide the number of values that we want.

In [ ]:
np.linspace(1,10,4)

In [ ]:
np.linspace(0,500,5)

# The 'EYE' function can be used or generating an identity matrix.

In [ ]:
np.eye(4,3) #an identity matrix has equal no of rows and comlumns.

In [ ]:
np.eye(3,3) #This is correct.

# RANDOM    (RAND, RANDN)

### RAND- It will generate the sequence from uniform distribiution. (Rectangle Graph)

#It will generate a sequence of digits with the help of a uniform distribution.
#The probability of each of the generated random numbers is equal hence it forms a rectangular graph.

In [ ]:
np.random.rand(5,5) #Here we created a matrix with the help of the random function.

In [ ]:
np.random.rand(5) #Here we generated a sequence of random digits.

### RANDN - It will generate a sequence from the  normal distribution (Bell Curve)


#It will generate a random seqeunce of values which lie under the curve.
#The area under the curve is equal to one.
#The mean, median and mode are equal.
#The normal curve will approach the x axis but will never touch it.
#Mean+ SD and Mean- SD will concave down and elsewhere it will go up.  The points where the graph changes it's concaavity iare called inflection points.

In [ ]:
np.random.randn(5) #Here 5  values were generated which were form normal distribution.

In [ ]:
np.random.randn(5,5) #Matrix from normal distribition.

## RandInt

It can be used for generating random values between a range.

In [ ]:
np.random.randint(1,10,4)  
#The first two arguments are the range and the third argumant is the number of values which have to be generated.

In [ ]:
np.random.randn(0,100,5)

# Reshaping

#We can reshape the elements of the array as per our requirements.

In [ ]:
arr = np.arange(0,20)

In [ ]:
arr


In [ ]:
arr.reshape(4,5)

### ArgMax , ArgMin, Max, Min

ArgMAX and ArgMIN are used for finding the location of the smallest and the largest element in the array.

The max and min command can be used for finding the maximum and minimum element in the array.

In [ ]:
arr1=np.random.randn(5,5)
arr1

In [ ]:
arr1.argmin() #Location of smallest element in the matrix.

In [ ]:
arr1.argmax() # Location of the largest element in the matrix.

In [ ]:
arr1.min() # The smallest value in the array.

In [ ]:
arr1.max() #The largest value in the array.

In [ ]:
arr1.shape  #This will tell us the shaoe of the array.

In [ ]:
arr2= np.arange(20)
arr2

In [ ]:
arr2.shape

# NUMPY Operations


In [70]:
arr3= np.arange(0,20)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr3 * arr3

In [ ]:
arr3 ++ arr3

In [ ]:
arr3 - arr3

In [ ]:
arr3 / arr3   # Here 0 was divided by 0 and it gave NaN.

In [ ]:
1 /arr3 # Here 0 was divided by infinity , hance it gave infinity.

In [ ]:
arr3 ** 3  #Double stars can be used for obtaining powers.

In [ ]:
np.sqrt(arr3)  #We use the sqrt function for getting the square root of the values in the array.

## Doubt What is exponent?


In [71]:
np.exp(arr3)  #For calculating the exponent. 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.max(arr3)

# doubt what is sin?


In [ ]:
np.sin(arr3)

In [ ]:
np.log(arr3)   #For getting the log values